# Generated by Django 6.0.2 on 2026-06-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_alter_profile_gender_challenge_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
