# Generated by Django 6.0.2 on 2026-07-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_stored_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('body_part', models.CharField(blank=True, db_index=True, max_length=100)),
                ('equipment', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target', models.CharField(blank=True, max_length=100)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('instructions', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('gif_url', models.URLField(blank=True, max_length=500)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('force', models.CharField(blank=True, max_length=50)),
                ('mechanic', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
